# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_token_and_survey_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('view_list_of_users', 'Can see the list of users'),)},
        ),
    ]
