# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_permission_to_see_list_of_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('view_list_of_users', 'Can see the list of users'), ('send_email_to_users', 'Can send email to users'))},
        ),
    ]
