# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('home_page', models.BooleanField(default=False, help_text='Enable this field if this is the home page',
                                                  verbose_name='Home page?')),
                ('enabled', models.BooleanField(default=False,
                                                help_text='Pages that are not enabled will not be listed in menu.',
                                                verbose_name='Enabled?')),
                ('link_order', models.IntegerField(blank=True, null=True, verbose_name='Position on the menu')),
                ('glyphicon', models.CharField(blank=True,
                                               help_text='Put here the icon you want to use, e.g. '
                                                         'glyphicon glyphicon-search', max_length=100)),
                ('posted', models.DateField(auto_now_add=True, verbose_name='Posted')),
            ],
            options={
                'ordering': ('-posted', 'translations__title'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('body', models.TextField(verbose_name='Body')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='translations', to='pages.Page')),
            ],
            options={
                'managed': True,
                'db_table': 'pages_page_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'page Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pagetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
