# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Link title'),
        ),
        migrations.AddField(
            model_name='page',
            name='submenu',
            field=models.BooleanField(default=False, help_text='Enable this field if you want this link as a submenu '
                                                               'of the main page link', verbose_name='Submenu'),
        ),
    ]
