# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtranslation',
            name='resume_summary',
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Institutional affiliation'),
        ),
    ]
