# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_resume_summary_add_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link_to_google',
            field=models.URLField(blank=True, null=True, verbose_name='Google'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link_to_iptv',
            field=models.URLField(blank=True, null=True, verbose_name='IPTV'),
        ),
    ]
