# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-04 11:39
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_link_to_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=blog.models.lecture_path, verbose_name='File')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_files', to='blog.Blog')),
            ],
        ),
    ]
