# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=b'', verbose_name='Project logo')),
            ],
            options={
                'verbose_name': 'Project logo',
                'permissions': (('change_project_logo', 'Can change the project logo.'),),
            },
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project name', max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Project name',
                'permissions': (('change_project_name', 'Can change the project name.'),),
            },
        ),
    ]
